### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by walrusthief** [ThereforeGames/txt2mask#13]
Okay so I was getting the Unpickling error and did the fix to delete the weights in clipseg and restarted but now I'm getting a new error.

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 134, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 58, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/img2img.py", line 115, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 158, in run
    processed = script.run(p, *script_args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/scripts/txt2mask.py", line 175, in run
    p.image_mask =  get_mask().resize((p.init_images[0].width,p.init_images[0].height))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/scripts/txt2mask.py", line 121, in get_mask
    model.load_state_dict(torch.load(d64_file, map_location=torch.device('cuda')), strict=False);
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

**Comment by ThereforeGames** [comment]
Hmm, I haven't seen that one before. Can you confirm that the two weights in `./respositories/clipseg/weights` are 4.2MB and 1MB?

If not, you may need to download the weights manually:

- https://owncloud.gwdg.de/index.php/s/ioHbRzFx6th32hn/download?path=%2F&files=rd64-uni.pth
- https://owncloud.gwdg.de/index.php/s/ioHbRzFx6th32hn/download?path=%2F&files=rd16-uni.pth

Also, it seems like your setup is connected to Google Drive - I wonder if that's causing an issue somehow.

**Comment by walrusthief** [comment]
Hmmm my previous weights were at 0 bytes so that was probs part of the problem. Manually downloaded the weights and it works fine now though!

**Comment by ThereforeGames** [comment]
Glad to hear it! I'll mark this as closed but feel free to let me know if you run into any other problems.
