### ISSUE TITLE
error at first step of img2mask

### ISSUE THREAD

**Issue by Ehplodor** [ThereforeGames/txt2mask#17]
Hi, I get the following error : 
0it [00:00, ?it/s]
Error completing request
Arguments: (1, 'photo of a man with beard and big eyes looking straight at camera, space stars and galaxies background', '', 'None', 'None', <PIL.Image.Image image mode=RGB size=1920x1786 at 0x22136802710>, {'image': <PIL.Image.Image image mode=RGBA size=512x512 at 0x22136802B00>, 'mask': <PIL.PngImagePlugin.PngImageFile image mode=RGBA size=512x512 at 0x22136801C00>}, None, None, 0, 100, 1, 4, 0, False, False, 1, 1, 12, 0, -1.0, -1.0, 0, 0, 0, False, 512, 512, 1, False, 32, 0, '', '', 9, 0, 0.1, 10, 7, 19.9, 0.1, 0.001, 'photo of a man with beard and eyes looking straight at camera, white wall background', '', -1, 50, 0, True, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, None, '', '<p style="margin-bottom:0.75em">Will upscale the image to twice the dimensions; use width and height sliders to set tile size</p>', 64, 0, 'background', '', 100, 0, 1, True, '<div class="gr-block gr-box relative w-full overflow-hidden border-solid border border-gray-200 gr-panel"><p>If you like my work, please consider showing your support on <strong><a href="https://patreon.com/thereforegames" target="_blank">Patreon</a></strong>. Thank you! &#10084;</p></div>', 1, '', 0, '', True, False) {}
Traceback (most recent call last):
  File "C:\AI\SD\AUTOMATIC1111\stable-diffusion-webui\modules\ui.py", line 184, in f
    res = list(func(*args, **kwargs))
  File "C:\AI\SD\AUTOMATIC1111\stable-diffusion-webui\webui.py", line 64, in f
    res = func(*args, **kwargs)
  File "C:\AI\SD\AUTOMATIC1111\stable-diffusion-webui\modules\img2img.py", line 124, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "C:\AI\SD\AUTOMATIC1111\stable-diffusion-webui\modules\scripts.py", line 159, in run
    processed = script.run(p, *script_args)
  File "C:\AI\SD\AUTOMATIC1111\stable-diffusion-webui\scripts\txt2mask.py", line 175, in run
    p.image_mask =  get_mask().resize((p.init_images[0].width,p.init_images[0].height))
  File "C:\AI\SD\AUTOMATIC1111\stable-diffusion-webui\scripts\txt2mask.py", line 111, in get_mask
    model = CLIPDensePredT(version='ViT-B/16', reduce_dim=64, complex_trans_conv=True)
TypeError: CLIPDensePredT.__init__() got an unexpected keyword argument 'complex_trans_conv'

thank you in advance.

**Comment by Ehplodor** [comment]
the clipseg repository you use is not up to date. see : https://github.com/timojl/clipseg/commit/ea54753df1e444c4445bac6e023546b6a41951d8
