### ISSUE TITLE
What's the error returned if it can't find/select anything from term?

### ISSUE THREAD

**Issue by Duemellon** [ThereforeGames/txt2mask#2]
I tried to get it to select "leaves, leaf" even tried "leafs" is there a way/place to visualize it's selection criteria before attempting to render?

``img2img: animal skulls, realistic
100%|███████████████████████████████████████| 335M/335M [00:07<00:00, 44.6MiB/s]
Error completing request
Arguments: ('animal skulls, realistic', '', 'None', 'None', <PIL.Image.Image image mode=RGB size=1024x1024 at 0x25CE318ADD0>, None, None, 0, 20, 0, 4, 0, False, False, 0, 1, 1, 7, 0.75, -1.0, -1.0, 0, 0, 0, 1024, 1024, 0, 0, 64, False, 0, 7, '', '', '', '', 1, 50, 0, 4, 1, 128, 4, 0, ['left', 'right', 'up', 'down'], None, False, 'leaves, leafs', 96, '<div class="gr-block gr-box relative w-full overflow-hidden border-solid border border-gray-200 gr-panel"><p>If you like my work, please consider showing your support on <strong><a href="https://patreon.com/thereforegames" target="_blank">Patreon</a></strong>. Thank you! &#10084;</p></div>', 1, '', 4, '', True) {}
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\modules\ui.py", line 125, in f
    res = list(func(*args, **kwargs))
  File "E:\stable-diffusion-webui\webui.py", line 71, in f
    res = func(*args, **kwargs)
  File "E:\stable-diffusion-webui\modules\img2img.py", line 131, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "E:\stable-diffusion-webui\modules\scripts.py", line 140, in run
    processed = script.run(p, *script_args)
  File "E:\stable-diffusion-webui\scripts\txt2mask.py", line 86, in run
    p.image_mask = get_mask()
  File "E:\stable-diffusion-webui\scripts\txt2mask.py", line 46, in get_mask
    model.load_state_dict(torch.load('./repositories/clipseg/weights/rd64-uni.pth', map_location=torch.device('cuda')), strict=False);
  File "E:\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

```

img2img: animal skulls, realistic
Error completing request
Arguments: ('animal skulls, realistic', '', 'None', 'None', <PIL.Image.Image image mode=RGB size=1024x1024 at 0x25CE31F3B80>, None, None, 0, 20, 0, 4, 0, False, False, 0, 1, 1, 7, 0.75, -1.0, -1.0, 0, 0, 0, 1024, 1024, 0, 0, 64, False, 0, 7, '', '', '', '', 1, 50, 0, 4, 1, 128, 4, 0, ['left', 'right', 'up', 'down'], None, False, 'leaf', 96, '<div class="gr-block gr-box relative w-full overflow-hidden border-solid border border-gray-200 gr-panel"><p>If you like my work, please consider showing your support on <strong><a href="https://patreon.com/thereforegames" target="_blank">Patreon</a></strong>. Thank you! &#10084;</p></div>', 1, '', 4, '', True) {}
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\modules\ui.py", line 125, in f
    res = list(func(*args, **kwargs))
  File "E:\stable-diffusion-webui\webui.py", line 71, in f
    res = func(*args, **kwargs)
  File "E:\stable-diffusion-webui\modules\img2img.py", line 131, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "E:\stable-diffusion-webui\modules\scripts.py", line 140, in run
    processed = script.run(p, *script_args)
  File "E:\stable-diffusion-webui\scripts\txt2mask.py", line 86, in run
    p.image_mask = get_mask()
  File "E:\stable-diffusion-webui\scripts\txt2mask.py", line 46, in get_mask
    model.load_state_dict(torch.load('./repositories/clipseg/weights/rd64-uni.pth', map_location=torch.device('cuda')), strict=False);
  File "E:\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.`

**Comment by ThereforeGames** [comment]
Hi,

Please see this thread for a possible workaround:

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/636#issuecomment-1250172740

> is there a way/place to visualize it's selection criteria before attempting to render?

Not at the moment, although the mask is saved as `mask.png` in the base directory of the web app after a successful run.

**Comment by ThereforeGames** [comment]
This should be resolved now - for some reason Github doesn't like to download the model files in this repo, so the script will fetch them for you at runtime. Let me know if the error persists.

Thanks!
