### ISSUE TITLE
Issues when trying to run the replacer

### ISSUE THREAD

**Issue by Delcos** [ThereforeGames/txt2mask#6]
img2img: A robot's arm
Error completing request
Arguments: ("A robot's arm", '', 'None', 'None', <PIL.Image.Image image mode=RGB size=944x958 at 0x1FDA7385690>, {'image': <PIL.Image.Image image mode=RGBA size=944x958 at 0x1FDA7387310>, 'mask': <PIL.PngImagePlugin.PngImageFile image mode=RGBA size=944x958 at 0x1FDA7384250>}, None, 0, 20, 0, 4, 0, False, False, 1, 1, 1, 7, 0.75, -1.0, -1.0, 0, 0, 0, 512, 512, 0, 0, 64, False, 0, 8, '', '', '', '', 1, 50, 0, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 4, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, None, '', False, 'robot', 96, '<div class="gr-block gr-box relative w-full overflow-hidden border-solid border border-gray-200 gr-panel"><p>If you like my work, please consider showing your support on <strong><a href="https://patreon.com/thereforegames" target="_blank">Patreon</a></strong>. Thank you! &#10084;</p></div>', 1, '', 4, '', True) {}
Traceback (most recent call last):
  File "C:\Users\USER\Documents\StableDiffusion\modules\ui.py", line 134, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\USER\Documents\StableDiffusion\webui.py", line 55, in f
    res = func(*args, **kwargs)
  File "C:\Users\USER\Documents\StableDiffusion\modules\img2img.py", line 131, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "C:\Users\USER\Documents\StableDiffusion\modules\scripts.py", line 159, in run
    processed = script.run(p, *script_args)
  File "C:\Users\USER\Documents\StableDiffusion\scripts\txt2mask.py", line 102, in run
    p.image_mask = get_mask()
  File "C:\Users\USER\Documents\StableDiffusion\scripts\txt2mask.py", line 62, in get_mask
    model.load_state_dict(torch.load(d64_file, map_location=torch.device('cuda')), strict=False);
  File "C:\Users\USER\Documents\StableDiffusion\venv\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\USER\Documents\StableDiffusion\venv\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

Any fixes known yet or am I missing something?

**Comment by ThereforeGames** [comment]
Hi, please try following the suggestions in this comment and let me know if it makes a difference for you:

https://github.com/ThereforeGames/txt2mask/issues/4#issuecomment-1250339501

**Comment by Delcos** [comment]
I already fixed that issue, I got something on the last few lines like :couldn't download from htttp:github......... so I manually did that, so I'm not sure that is causing this.
